### ISSUE TITLE
Add deployment target for EMR on EC2

### ISSUE THREAD

**Issue by dacort** [awslabs/amazon-emr-vscode-toolkit#11]
Add EMR on EC2 clusters as a new deployment option similar to "EMR Serverless: Run job"

If you're interested in this feature, please 👍 and leave a comment below with how you deploy to EMR on EC2 today to help inform how this feature is built. For example, do you have a CI/CD pipeline already that deploys assets? Do you want to publish a local file? Are you using pyspark/scala/sql? How is your project structured today?

**Comment by sreelakshman** [comment]
would like to run and test pyspark jobs run on emr on ec2 from vscode itself (while developing)

**Comment by dacort** [comment]
Got it, so just copying up a single pyspark script with no dependencies. Thanks!

**Comment by dacort** [comment]
Added initial support for this in 0.6.0.

**Comment by sreelakshman** [comment]
Hi @dacort 
can we now deploy py scritps to emr on ec2 from vscode?

**Comment by dacort** [comment]
Yes, in the most recent version there is a "EMR on EC2: run job" command. It only supports a single py file, but feel free to give it a shot and let me know how it goes. 

If you have a more complex setup (multiple py files, 3rd-party dependencies), you can also try the [emr-cli](https://github.com/awslabs/amazon-emr-cli).
