### ISSUE TITLE
Allow search in Glue Table details window

### ISSUE THREAD

**Issue by dgilmanAIDENTIFIED** [awslabs/amazon-emr-vscode-toolkit#19]
If you pull up the Glue Table detail window (Glue Catalog Explorer -> right click on a table -> View Glue Table), you can't do a regular ctrl-f search on the contents of that window. It would be nice to search.

**Comment by dacort** [comment]
Hi @dgilmanAIDENTIFIED thanks for opening a new issue! That definitely would be useful, I'll look into how hard it will be to implement.
