### ISSUE TITLE
Support for EMR 6.10.0

### ISSUE THREAD

**Issue by ramondiez** [awslabs/amazon-emr-vscode-toolkit#24]
Nowadays EMR Toolkit supports untill EMR 6.9.0. It would be great to have the capability deploy EMR 6.10.0 that comes with a new Iceberg version.

**Comment by dacort** [comment]
Will merge in an update to handle this - in the meantime, you can edit the `devcontainer.json` and change the `RELEASE` arg to `emr-6.10.0`, then "rebuild container".

**Comment by dacort** [comment]
Added in 0.6.0
